# Generated by Django 5.1.6 on 2025-02-19 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailing"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampaignAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_attempt", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("status_ok", "Успешно"), ("status_nok", "Неуспешно")],
                        max_length=10,
                    ),
                ),
                ("server_response", models.TextField()),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempts",
                        to="mailings.mailing",
                    ),
                ),
            ],
        ),
    ]
