# Generated by Django 5.1.6 on 2025-02-19 12:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_campaignattempt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="campaignattempt",
            old_name="campaign",
            new_name="mailing",
        ),
        migrations.AlterField(
            model_name="campaignattempt",
            name="date_attempt",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="campaignattempt",
            name="status",
            field=models.CharField(
                choices=[("status_ok", "Успешно"), ("status_nok", "Не успешно")],
                max_length=10,
            ),
        ),
    ]
