# Generated by Django 5.1.6 on 2025-03-10 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_message_options_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [("change_all_mailings", "Can change all mailings")]
            },
        ),
    ]
